function onOpen() {
  var ui = SpreadsheetApp.getUi();
  ui.createMenu('Importadora Elizalde')
      .addItem('Registrar Venta', 'registrarVenta')
      .addSeparator()
      .addItem('Recalcular Saldo', 'calculaSaldo')
      .addSeparator()
      .addItem('Generar Respaldo', 'respaldoImportadoraElizalde')
      .addSeparator()
      .addItem('Probar Lógica Lead Time', 'lead_time_logic')
      .addToUi();
  ui.createMenu('Marketplace')
      .addSubMenu(ui.createMenu('Mercado Libre')
          .addItem('Consultar productos', 'consultaProdsML')
          .addSeparator()
          .addItem('Consultar ventas histórico', 'ingestarVentasMLC_historico')
          .addItem('Consultar ventas incremental', 'ingestarVentasMLC_incremental')
          .addItem('Conciliar ventas', 'mlc_conciliar')
          .addSeparator()
          .addItem('Actualizar stock', 'actualizarStockML')
          .addItem('Actualizar estado', 'actualizarEstadoML')
          .addItem('Actualizar precios', 'actualizarPreciosML')
          .addItem('Actualizar precios oferta', 'f')
          .addSeparator()
          .addItem('Solicitar Accesos', 'refreshMeliTokens')
        )
      .addSubMenu(ui.createMenu('Falabella')
          .addItem('Consultar productos', 'consultaProdsFS')
          .addSeparator()
          .addItem('Consultar ventas histórico', 'fsc_ingestaHistorica')
          .addItem('Consultar ventas incremental', 'fsc_ingestaIncremental')
          .addItem('Conciliar ventas', 'fsc_conciliar')
          .addSeparator()
          .addItem('Actualizar stock', 'actualizarStockFS')
          .addItem('Actualizar status', 'actualizarStatusFS')
          .addItem('Actualizar precios', 'actualizarPreciosFS')
          .addItem('Actualizar precios oferta', 'actualizarPreciosOfertaFS')
        )
      .addSubMenu(ui.createMenu('Paris')
          .addItem('Consultar todo', 'paris_runAll_fetchs')
          .addItem('Consultar precios', 'paris_fetchPrices_toSheet')
          .addItem('Consultar productos', 'paris_fetchProducts_mapSkus')
          .addSeparator()
          .addItem('Consultar ventas histórico', 'pm_ingestaHistorica')
          .addItem('Consultar ventas incremental', 'pm_ingestaIncremental')
          .addItem('Conciliar ventas', 'pm_conciliar')
          .addSeparator()
          .addItem('Actualizar stock', 'paris_updateStock_fromSheet')
          .addItem('Actualizar precios', 'paris_updatePriceList_fromSheet')
          .addItem('Actualizar precios oferta', 'paris_updatePriceOffer_fromSheet')
          .addSeparator()
          .addItem('Limpiar cache', 'paris_clearCache')
          .addItem('Limpiar cache Parent Id', 'paris_clearParentIdCache_')
        )
      .addSubMenu(ui.createMenu('Shopify')
          .addItem('Consultar productos', 'syncShopifyProductsToSheet')
          .addSeparator()
          .addItem('Consultar ventas histórico',   'sh_ingestaHistorica')
          .addItem('Consultar ventas incremental', 'sh_ingestaIncremental')
          .addItem('Conciliar ventas',             'sh_conciliar')
          .addSeparator()
          .addItem('Actualizar stock', 'updateShopifyStockOnly')
          .addItem('Actualizar status', 'updateShopifyStatusOnly')
          .addItem('Actualizar precios', 'updateShopifyPriceOnly')
          .addItem('Actualizar precios oferta', 'updateShopifyFromSheet')
          .addSeparator()
          .addItem('Actualizar título', 'updateShopifyTitlesFromSheet')
          .addItem('Actualizar metacampos SEO', 'updateShopifySeoFromSheet')
        )
      .addToUi(); 
}